ammar_portfolio_basic/urls.py
from portfolio_code.apps import PortfolioCodeConfig
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio_code.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blog, name='all_blog'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

portfolio_code/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.Home, name='home')
]

blog/models.py
from django.db import models

# Create your models here.


class Blogs(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio_code/models.py
from django.db import models

# Create your models here.


class project(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio_code/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from .models import Blogs

# Create your views here.


def all_blog(request):

    # blog = Blogs.objects.order_by('-date')
    # blog = Blogs.objects.order_by('-date')[:5]
    blog = Blogs.objects.all()
    context = {'blog': blog}
    return render(request, 'blog/blogs.html', context)


def detail(request, blog_id):
    blog = get_object_or_404(Blogs, pk=blog_id)
    context = {'id': blog_id, 'blog': blog}
    return render(request, 'blog/detail.html', context)

portfolio_code/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import project

# Create your views here.


def Home(request):

    proj = project.objects.all()
    context = {'proj': proj}
    return render(request, 'portfolio_code/Home.html', context)

blog/templates/blog/blogs.html
{% extends 'portfolio_code/base.html' %}
{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>
<h3 class="text-center mb-5">Ammar has written {{blog.count}} blog{{ blog.count|pluralize }} </h3>

{% for bl in blog %}
<div class="row justify-content-center my-3">
    <div class="col-md-10">
        <h3><a href="{% url 'blog:detail' bl.id %}">{{bl.title}}</a></h3> <br>
        <h5 class="text-muted">{{bl.date|date:'M d Y'| upper}}</h5><br><br>
        <h4>{{bl.description|striptags|truncatechars:250}}</h4> <br><br>
    </div>
</div>
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio_code/base.html' %}
{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>
<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5> <br>
{{ blog.description|safe }}

{% endblock %}

portfolio_code/templates/portfolio_code/Home.html
{% extends 'portfolio_code/base.html' %}
{% load static %}
{% block content %}
<!-- <h2>Ammar's Portfolio</h2>
<a href="{% url 'blog:all_blog' %}">Blog</a> -->



<div class="row justify-content-center my-3">
    <div class="col-5">
        <img src="{% static 'portfolio_code/Ammar_Profile-bg.png' %}" class="img-fluid">
    </div>
</div>

<div class="row justify-content-center mb-3">
    <div class="col-md-9 text-center">
        <h1 id="hometext" class="font-weight-bold">Python | Django Developer | Machine Learning 😊</h1>
    </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
    {% for project in proj %}
    <div class="col-lg-4 col-md-6">
        {% if project.url %}
        <br><a href="{{project.url}}"><img src="{{ project.image.url }}" class="img-fluid mb-2"></a><br>


        {% else %}

        <img src="{{project.image.url}}" class="img-fluid mb-2">
        {% endif %}
        {{project.title}} <br>
        {{project.description}}
    </div>
    {% endfor %}
</div>
{% endblock %}

portfolio_code/templates/portfolio_code/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

    <link rel="icon" type="image/png" href="{% static 'portfolio/Logo.png' %}">

    <title>Ammar's Portfolio</title>
</head>

<body>
    <nav id="topNav" class="navbar navbar-expand-md navbar-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'portfolio_code/Logo.png' %}" width="30" height="30"
                    class="d-inline-block align-top" alt="Ammar's Logo">
                <span>Ammar Altaf</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse text-center" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% static 'portfolio_code/resume.pdf' %}">Resume</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://www.linkedin.com/in/mammaraltaf" target="_blank">LinkedIn</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://github.com/mammaraltaf" target="_blank">GitHub</a>
                    </li>
                    <li>
                        <a role="button" href="{% url 'blog:all_blog' %}" class="btn btn-primary">Blog</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>